# AI Configuration Setup Script
# Run this to configure AI features for your quiz app

import os
import sys
import json
from pathlib import Path

def setup_ai_config():
    """Interactive setup for AI configuration"""
    print("🤖 Quiz App AI Features Configuration")
    print("=" * 50)
    print()
    
    config = {}
    
    # OpenAI Configuration
    print("📝 OpenAI Configuration:")
    openai_key = input("Enter your OpenAI API key (or press Enter to skip): ").strip()
    if openai_key:
        config['OPENAI_API_KEY'] = openai_key
        model = input("OpenAI model (default: gpt-3.5-turbo): ").strip() or "gpt-3.5-turbo"
        config['OPENAI_MODEL'] = model
    
    print()
    
    # Anthropic Configuration
    print("📝 Anthropic Configuration:")
    anthropic_key = input("Enter your Anthropic API key (or press Enter to skip): ").strip()
    if anthropic_key:
        config['ANTHROPIC_API_KEY'] = anthropic_key
        model = input("Anthropic model (default: claude-3-sonnet-20240229): ").strip() or "claude-3-sonnet-20240229"
        config['ANTHROPIC_MODEL'] = model
    
    print()
    
    # Feature Configuration
    print("⚙️ Feature Configuration:")
    features = {
        'ENABLE_QUESTION_GENERATION': input("Enable AI question generation? (y/N): ").lower().startswith('y'),
        'ENABLE_PERSONALIZED_LEARNING': input("Enable personalized learning? (y/N): ").lower().startswith('y'),
        'ENABLE_AI_EXPLANATIONS': input("Enable AI explanations? (y/N): ").lower().startswith('y'),
        'CHATBOT_ENABLED': input("Enable AI chatbot? (y/N): ").lower().startswith('y'),
    }
    
    config.update({k: str(v).lower() for k, v in features.items()})
    
    # Save to .env file
    env_file = Path('.env')
    existing_config = {}
    
    # Read existing .env if it exists
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                if '=' in line and not line.startswith('#'):
                    key, value = line.strip().split('=', 1)
                    existing_config[key] = value
    
    # Update with new config
    existing_config.update(config)
    
    # Write back to .env
    with open(env_file, 'w') as f:
        f.write("# Quiz App Configuration\n")
        f.write("# Generated by AI setup script\n\n")
        
        f.write("# Database Configuration\n")
        if 'DATABASE_URL' in existing_config:
            f.write(f"DATABASE_URL={existing_config['DATABASE_URL']}\n")
        if 'POSTGRES_PASSWORD' in existing_config:
            f.write(f"POSTGRES_PASSWORD={existing_config['POSTGRES_PASSWORD']}\n")
        f.write("\n")
        
        f.write("# AI Configuration\n")
        for key, value in config.items():
            f.write(f"{key}={value}\n")
        f.write("\n")
        
        # Add any other existing config
        for key, value in existing_config.items():
            if key not in config and not key.startswith(('DATABASE_URL', 'POSTGRES_PASSWORD')):
                f.write(f"{key}={value}\n")
    
    print()
    print("✅ Configuration saved to .env file")
    print()
    
    # Install dependencies if needed
    if any(key.endswith('_API_KEY') for key in config.keys()):
        print("📦 Installing AI dependencies...")
        install_deps = input("Install AI dependencies now? (Y/n): ").strip()
        if not install_deps.lower().startswith('n'):
            install_ai_dependencies()
    
    print()
    print("🎉 AI configuration complete!")
    print()
    print("Next steps:")
    print("1. Restart your application: ./dev.sh restart")
    print("2. Check AI status: curl http://localhost:9080/api/ai/status")
    print("3. Try the AI features in your quiz app!")

def install_ai_dependencies():
    """Install AI dependencies"""
    try:
        import subprocess
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-r', 'requirements-ai.txt'], check=True)
        print("✅ AI dependencies installed successfully")
    except subprocess.CalledProcessError as e:
        print(f"❌ Error installing dependencies: {e}")
        print("You can install manually with: pip install -r requirements-ai.txt")
    except Exception as e:
        print(f"❌ Unexpected error: {e}")

def check_ai_status():
    """Check current AI configuration status"""
    print("🔍 Checking current AI configuration...")
    
    try:
        from ai_config import validate_ai_setup
        status = validate_ai_setup()
        
        print("\n📊 AI Status:")
        print(f"OpenAI Available: {'✅' if status['openai_available'] else '❌'}")
        print(f"Anthropic Available: {'✅' if status['anthropic_available'] else '❌'}")
        print(f"Overall Ready: {'✅' if status['ready'] else '❌'}")
        
        print("\n⚙️ Feature Status:")
        for feature, enabled in status['features_enabled'].items():
            print(f"{feature.replace('_', ' ').title()}: {'✅' if enabled else '❌'}")
    
    except ImportError:
        print("❌ AI modules not available. Install dependencies first.")
    except Exception as e:
        print(f"❌ Error checking status: {e}")

def create_sample_questions():
    """Generate sample questions using AI"""
    print("🧪 Generating sample questions...")
    
    try:
        import asyncio
        from question_generator import generate_questions_for_category
        
        async def generate_samples():
            questions = await generate_questions_for_category(
                category="general",
                count=3,
                difficulty="intermediate"
            )
            
            print("\n📝 Sample Generated Questions:")
            for i, q in enumerate(questions, 1):
                print(f"\nQuestion {i}:")
                print(f"  Text: {q['text']}")
                print(f"  Choices: {q['choices']}")
                print(f"  Answer: {q['correct_answer']}")
                print(f"  Confidence: {q['confidence']:.1%}")
        
        asyncio.run(generate_samples())
        
    except ImportError:
        print("❌ AI modules not available. Configure and install dependencies first.")
    except Exception as e:
        print(f"❌ Error generating questions: {e}")

def main():
    """Main CLI interface"""
    if len(sys.argv) > 1:
        command = sys.argv[1].lower()
        
        if command == 'setup':
            setup_ai_config()
        elif command == 'status':
            check_ai_status()
        elif command == 'test':
            create_sample_questions()
        elif command == 'install':
            install_ai_dependencies()
        else:
            print(f"Unknown command: {command}")
            print_usage()
    else:
        print_usage()

def print_usage():
    """Print usage information"""
    print("🤖 AI Configuration Tool")
    print("Usage: python ai_setup.py <command>")
    print()
    print("Commands:")
    print("  setup   - Interactive AI configuration")
    print("  status  - Check current AI status")
    print("  test    - Generate sample questions")
    print("  install - Install AI dependencies")
    print()
    print("Examples:")
    print("  python ai_setup.py setup")
    print("  python ai_setup.py status")

if __name__ == '__main__':
    main()